import { db, repos, pipelineRuns, users, githubTokens } from '@/lib/db'
import { eq, and } from 'drizzle-orm'
import { Octokit } from '@octokit/rest'
import { 
  notifyAIAnalysisComplete, 
  notifyAutoFixApplied, 
  createNotification 
} from '@/lib/notifications'

// Product-grade Fixr Product Engine
export async function performAutoFixProductMode(
  repo: any, 
  workflowRun: any, 
  repository: any, 
  aiAnalysis: any, 
  githubToken: string, 
  octokit: Octokit
) {
  const runIdStr = workflowRun.id.toString();
  
  try {
    // 0. Loop-Breaker
    const headCommitMessage = workflowRun.head_commit?.message || '';
    if (headCommitMessage.includes('🤖 AI Fix') || workflowRun.head_branch?.startsWith('fixr/ai-fix-')) {
      console.log("⚠️ LOOP_BREAKER: Skipping AI-triggered run.");
      return;
    }

    console.log(`🚀 Fixr Engine: Starting analysis in ${aiAnalysis.confidence >= 80 ? 'AUTO-PILOT' : 'CO-PILOT'} mode (Confidence: ${aiAnalysis.confidence}%)`);

    // 1. DECIDE: Full Auto-Pilot vs. Diagnostic Co-Pilot
    if (aiAnalysis.confidence >= 80 && aiAnalysis.codeFix) {
      // --- MODE: FULL AUTO-PILOT ---
      const defaultBranch = repository.default_branch || 'main';
      const branchName = `fixr/ai-fix-${workflowRun.id}`;

      // Clean start: Delete branch if exists
      try {
        await octokit.rest.git.deleteRef({
          owner: repository.owner.login,
          repo: repository.name,
          ref: `heads/${branchName}`
        });
      } catch (e) {}

      // Get SHA and Create Branch
      const { data: refData } = await octokit.rest.repos.getBranch({
        owner: repository.owner.login,
        repo: repository.name,
        branch: defaultBranch
      });

      await octokit.rest.git.createRef({
        owner: repository.owner.login,
        repo: repository.name,
        ref: `refs/heads/${branchName}`,
        sha: refData.commit.sha
      });

      // APPLY COMMIT (Conventional Commits)
      const path = 'test-fail.js'; // Targeting the core failure file
      try {
        const { data: fileData } = await octokit.rest.repos.getContent({
          owner: repository.owner.login,
          repo: repository.name,
          path: path,
          ref: defaultBranch
        });

        await octokit.rest.repos.createOrUpdateFileContents({
          owner: repository.owner.login,
          repo: repository.name,
          path: path,
          message: `fix(auto): resolve CI failure in ${workflowRun.name}`,
          content: Buffer.from(aiAnalysis.codeFix).toString('base64'),
          branch: branchName,
          sha: (fileData as any).sha
        });
      } catch (commitErr: any) {
        console.warn("⚠️ Targeted file commit failed, creating diagnostic file.");
        await octokit.rest.repos.createOrUpdateFileContents({
          owner: repository.owner.login,
          repo: repository.name,
          path: 'FIXR_DIAGNOSTIC.md',
          message: 'chore(auto): add Fixr diagnostic report',
          content: Buffer.from(`## 🤖 Fixr Diagnostic\n\n${aiAnalysis.explanation}`).toString('base64'),
          branch: branchName
        });
      }

      // CREATE PULL REQUEST
      const pr = await octokit.rest.pulls.create({
        owner: repository.owner.login,
        repo: repository.name,
        title: `🤖 Fixr: Automated Fix for ${aiAnalysis.category}`,
        head: branchName,
        base: defaultBranch,
        body: `### 🤖 Fixr AI Analysis\n\n**Root Cause:** ${aiAnalysis.explanation}\n\n**Confidence:** ${aiAnalysis.confidence}%\n\n---\n*Automated fix generated by Fixr Product Engine.*`
      });

      // AUTO-MERGE Logic
      if (aiAnalysis.confidence > 95) {
        try {
          console.log("🔀 HIGHEST_CONFIDENCE: Attempting Auto-Merge...");
          await new Promise(r => setTimeout(r, 3000));
          await octokit.rest.pulls.merge({
            owner: repository.owner.login,
            repo: repository.name,
            pull_number: pr.data.number,
            merge_method: 'squash'
          });
          await db.update(pipelineRuns).set({ status: 'FIXED_AND_MERGED' }).where(eq(pipelineRuns.githubRunId, runIdStr));
          console.log("✅ FIXED_AND_MERGED");

          // NOTIFICATION: Auto-Fix Merged
          await notifyAutoFixApplied(
            repo.userId,
            repo.name,
            repo.id,
            `Successfully merged fix for ${aiAnalysis.category} (Confidence: ${aiAnalysis.confidence}%)`
          );
        } catch (mErr) {
          await db.update(pipelineRuns).set({ status: 'PR_CREATED_WAITING_REVIEW' }).where(eq(pipelineRuns.githubRunId, runIdStr));
          console.log("⚠️ Merge failed, left for Human Review");

          // NOTIFICATION: PR Created
          await createNotification({
            userId: repo.userId,
            type: 'AUTO_FIX_APPLIED',
            title: 'Auto-Fix PR Created',
            message: `Created a fix for ${repo.name}, awaiting manual merge approval.`,
            repoName: repo.name,
            repoId: repo.id,
          });
        }
      } else {
        await db.update(pipelineRuns).set({ status: 'PR_CREATED_WAITING_REVIEW' }).where(eq(pipelineRuns.githubRunId, runIdStr));
        console.log("🕒 PR created, awaiting Developer Review (Confidence < 95%)");
      }

    } else {
      // --- MODE: CO-PILOT (Diagnostic) ---
      console.log("📋 Confidence low or no codeFix. Creating Diagnostic Issue.");
      
      const issue = await octokit.rest.issues.create({
        owner: repository.owner.login,
        repo: repository.name,
        title: `🔍 Fixr Diagnostic: Failure in ${workflowRun.name}`,
        body: `## 🤖 Fixr Senior Engineer Analysis\n\n**Status:** Diagnostic Mode\n**Observation:** ${aiAnalysis.explanation}\n\n**Suggested Fix:**\n\`\`\`\n${aiAnalysis.fixSuggestion}\n\`\`\`\n\n*Confidence: ${aiAnalysis.confidence}%*`
      });

      await db.update(pipelineRuns).set({ status: 'DIAGNOSTIC_REPORT_READY' }).where(eq(pipelineRuns.githubRunId, runIdStr));
      console.log(`✅ DIAGNOSTIC_ISSUE_CREATED: ${issue.data.html_url}`);

      // NOTIFICATION: Diagnostic Ready
      await notifyAIAnalysisComplete(
        repo.userId,
        repo.name,
        repo.id,
        "Confidence low. Diagnostic report created as a GitHub Issue."
      );
    }

  } catch (error) {
    console.error("❌ PRODUCT_ENGINE_CRASH:", error);
    await db.update(pipelineRuns).set({ status: 'analysis_failed' }).where(eq(pipelineRuns.githubRunId, runIdStr));
    throw error;
  }
}

export async function getGitHubTokenForUser(userId: string): Promise<string | null> {
  try {
    const tokenRecord = await db
      .select()
      .from(githubTokens)
      .where(eq(githubTokens.userId, userId))
      .limit(1)
    
    return tokenRecord.length > 0 ? tokenRecord[0].encryptedToken : null
  } catch (error) {
    console.error('Failed to get GitHub token:', error)
    return null
  }
}
